language: bash
sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
services:
  - docker
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=inyee/github-bot;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO; 
  fi
- if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=inyee/github-bot;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"&& docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO; 
  fi